version: '3.5'
services:
  main:
    image: quanlill/main_office_face_recognition_gpu
    # restart: always
    build: .
    ports:
      - "5001:5001" #machine:docker
    volumes:
      - /fr_test:/data
    networks:
      app_net:

        # deploy gpu
    deploy:
      # replicas: 5
      # restart_policy:
      #   condition: on-failure
      resources:
        reservations:
          generic_resources:
            - discrete_resource_spec:
                kind: 'NVIDIA-GPU'
                value: 0
      #   reservations:
      #     devices:
      #       - driver: nvidia
      #         count: 1
      #         capabilities: [ gpu ]

networks:
  app_net:
    name: face_recognition
    external: true
