version: '3.5'
services:
  main:
    image: quanlill/main_office_face_recognition_cpu
    # restart: always
    build: .
    ports:
      - "5001:5001" #machine:docker

    networks:
      app_net:

        # deploy gpu
    deploy:
      # replicas: 5
      # restart_policy:
      #   condition: on-failure
      # resources:
      #   reservations:
      #     devices:
      #       - driver: nvidia
      #         count: 1
      #         capabilities: [ gpu ]

networks:
  app_net:
    name: face_recognition
    external: true
